"""
===============================================================================
Enterprise Financial Analytics Platform (EFAP)
-------------------------------------------------------------------------------
Object          : business_event_type.py
Object Type     : Business Event Types
Layer           : Domain
Version         : 1.0.0
Status          : Development
===============================================================================
"""

from enum import Enum


class BusinessEventType(str, Enum):
    """
    Supported business events.
    """

    SALES_INVOICE = "SALES_INVOICE"

    PURCHASE_INVOICE = "PURCHASE_INVOICE"

    CUSTOMER_PAYMENT = "CUSTOMER_PAYMENT"

    SUPPLIER_PAYMENT = "SUPPLIER_PAYMENT"

    PAYROLL = "PAYROLL"

    DEPRECIATION = "DEPRECIATION"


    ASSET_ACQUISITION = "ASSET_ACQUISITION"
    ASSET_CAPITALIZATION = "ASSET_CAPITALIZATION"
    ASSET_DEPRECIATION = "ASSET_DEPRECIATION"
    ASSET_TRANSFER = "ASSET_TRANSFER"
    ASSET_IMPAIRMENT = "ASSET_IMPAIRMENT"
    ASSET_REVALUATION = "ASSET_REVALUATION"
    ASSET_DISPOSAL = "ASSET_DISPOSAL"
    ASSET_SALE = "ASSET_SALE"

    INVENTORY_RECEIPT = "INVENTORY_RECEIPT"
    INVENTORY_ISSUE = "INVENTORY_ISSUE"
    INVENTORY_TRANSFER = "INVENTORY_TRANSFER"
    INVENTORY_ADJUSTMENT = "INVENTORY_ADJUSTMENT"
    INVENTORY_WRITEOFF = "INVENTORY_WRITEOFF"
    INVENTORY_REVALUATION = "INVENTORY_REVALUATION"

    PAYROLL_EXPENSE = "PAYROLL_EXPENSE"
    EMPLOYER_CONTRIBUTION = "EMPLOYER_CONTRIBUTION"
    PAYROLL_PAYMENT = "PAYROLL_PAYMENT"
    PAYROLL_TAX = "PAYROLL_TAX"
    PAYROLL_BONUS = "PAYROLL_BONUS"
    VACATION_ACCRUAL = "VACATION_ACCRUAL"
    OVERTIME = "OVERTIME"
    PAYROLL_REVERSAL = "PAYROLL_REVERSAL"

    BANK_FEE = "BANK_FEE"
    INTEREST_INCOME = "INTEREST_INCOME"
    INTEREST_EXPENSE = "INTEREST_EXPENSE"
    FX_GAIN = "FX_GAIN"
    FX_LOSS = "FX_LOSS"
    LOAN_DRAWDOWN = "LOAN_DRAWDOWN"
    LOAN_REPAYMENT = "LOAN_REPAYMENT"
    CASH_DEPOSIT = "CASH_DEPOSIT"
    CASH_WITHDRAWAL = "CASH_WITHDRAWAL"
    INTERNAL_TRANSFER = "INTERNAL_TRANSFER"

    ACCRUED_EXPENSE = "ACCRUED_EXPENSE"
    ACCRUED_REVENUE = "ACCRUED_REVENUE"
    PREPAID_EXPENSE = "PREPAID_EXPENSE"
    DEFERRED_REVENUE = "DEFERRED_REVENUE"
    PROVISION = "PROVISION"
    FX_REVALUATION = "FX_REVALUATION"
    YEAR_END = "YEAR_END"
    PERIOD_CLOSE = "PERIOD_CLOSE"
    BAD_DEBT_ALLOWANCE = "BAD_DEBT_ALLOWANCE"
    FOREIGN_CURRENCY_REVALUATION = "FOREIGN_CURRENCY_REVALUATION"
    INCOME_TAX_ACCRUAL = "INCOME_TAX_ACCRUAL"

   