/*
 ===============================================================================
 Enterprise Financial Analytics Platform (EFAP)
 -------------------------------------------------------------------------------
 Object          : validation_documents.sql
 Object Type     : Validation Script
 Layer           : Database Validation
 Version         : 1.0.0
 Status          : Development
 -------------------------------------------------------------------------------
 Description:
 Validates accounting documents generated by the ETL process.
 ===============================================================================
 */
-- ============================================================================
-- 1. Documents by type
-- ============================================================================
SELECT document_type,
    COUNT(DISTINCT document_number) AS document_count,
    COUNT(*) AS journal_rows
FROM warehouse.fact_gl
GROUP BY document_type
ORDER BY document_type;

-- ============================================================================
-- 2. Journal lines per document
-- ============================================================================
SELECT document_type,
    document_number,
    COUNT(*) AS line_count
FROM warehouse.fact_gl
GROUP BY document_type,
    document_number
ORDER BY document_type,
    document_number;
-- ============================================================================
-- 3. Average number of journal lines per document
-- ============================================================================
SELECT document_type,
    ROUND(AVG(line_count), 2) AS average_lines
FROM (
        SELECT document_type,
            document_number,
            COUNT(*) AS line_count
        FROM warehouse.fact_gl
        GROUP BY document_type,
            document_number
    ) x
GROUP BY document_type
ORDER BY document_type;
-- ============================================================================
-- 4. Minimum and maximum document number
-- ============================================================================
SELECT document_type,
    MIN(document_number) AS first_document,
    MAX(document_number) AS last_document
FROM warehouse.fact_gl
GROUP BY document_type
ORDER BY document_type;
-- ============================================================================
-- 5. Duplicate document numbers
-- ============================================================================
SELECT document_type,
    document_number,
    COUNT(*) AS occurrences
FROM (
        SELECT DISTINCT document_type,
            document_number,
            line_number
        FROM warehouse.fact_gl
    ) t
GROUP BY document_type,
    document_number
HAVING COUNT(*) > 20
ORDER BY document_type,
    document_number;
-- ============================================================================
-- 6. Documents with only one journal line
-- ============================================================================
SELECT document_type,
    document_number,
    COUNT(*) AS line_count
FROM warehouse.fact_gl
GROUP BY document_type,
    document_number
HAVING COUNT(*) = 1
ORDER BY document_type,
    document_number;
-- ============================================================================
-- 7. Missing document numbers
-- ============================================================================
SELECT *
FROM warehouse.fact_gl
WHERE document_number IS NULL;
-- ============================================================================
-- 8. Missing document types
-- ============================================================================
SELECT *
FROM warehouse.fact_gl
WHERE document_type IS NULL;